version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./src:/LabWork2/src
      - ./include:/LabWork2/include
    working_dir: /LabWork2
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm-256color
    command: bash -c "stty sane && ./run_game"
