name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++ make


    - name: Install Google Test
      run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -S . -B build
          cmake --build build
          sudo cmake --install build  # Installs gtest globally


    - name: Build project
      run: make -C tests

    - name: Run tests
      run: ./test
