name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ make  

      - name: Build project
        run: make  

      - name: Run tests
        run: make test 
