name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++ make

    - name: Build project
      run: make -C ~/Desktop/LabWork2/Lbawork2/tests/Makefile

    - name: Run tests
      run: ./test
